# Generated by Django 4.1.7 on 2023-03-18 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="per_page_default",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
